# Generated by Django 3.1.4 on 2020-12-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filtered_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
